image: ubuntu:16.04

build:
  stage: build
  script:
  - apt-get -qq update && apt-get -qq install git curl wget 2> /dev/null
  - wget -q https://github.com/fabianonline/telegram.sh/raw/master/telegram && chmod +x telegram
  - chmod +x *.sh
  - ./script.sh
